-- Demo DDL script
-- Richard Marquez Revature Associate Workbook assignment

-- Section 1

-- Problem 1.1: Write script to .....

CREATE TABLE DEMO_CUSTOMERS
(
CUSTOMER_ID NUMBER PRIMARY KEY,
CUST_FIRST_NAME VARCHAR2(50) NOT NULL,
CUST_LAST_NAME VARCHAR2(50) NOT NULL,
CUST_STATE VARCHAR2(2CHAR),
CREDIT_LIMIT NUMBER(9,2), -- 9 digits total, 2 after decimal
CUST_EMAIL VARCHAR2(100)
);

CREATE TABLE DEMO_ORDERS
(
ORDER_ID NUMBER,
CUSTOMER_ID NUMBER,
ORDER_TOTAL NUMBER(9,2),
ORDER_TIMESTAMP DATE,
USER_ID NUMBER,

PRIMARY KEY(ORDER_ID),
FOREIGN KEY(CUSTOMER_ID) REFERENCES DEMO_CUSTOMERS(CUSTOMER_ID)
);

TRUNCATE TABLE examples.DEMO_CUSTOMERS;
SELECT * FROM DEMO_CUSTOMERS;


-- customer data
INSERT INTO DEMO_CUSTOMERS (CUST_FIRST_NAME, CUST_LAST_NAME, CUST_STATE, CREDIT_LIMIT, CUST_EMAIL)
  VALUES ('Richard', 'Marquez', 'CA', 780, 'richard92m@me.com');

INSERT INTO DEMO_CUSTOMERS (CUST_FIRST_NAME, CUST_LAST_NAME, CUST_STATE, CREDIT_LIMIT, CUST_EMAIL)
  VALUES ('Bob', 'Dylan', 'CA', 700.21, 'bobby_d@me.com');
  
INSERT INTO DEMO_CUSTOMERS (CUST_FIRST_NAME, CUST_LAST_NAME, CUST_STATE, CREDIT_LIMIT, CUST_EMAIL)
  VALUES ('Saul', 'Hudson', 'CA', 12, 'slash@gmail.com');
  
INSERT INTO DEMO_CUSTOMERS (CUST_FIRST_NAME, CUST_LAST_NAME, CUST_STATE, CREDIT_LIMIT, CUST_EMAIL)
  VALUES ('Axl', 'Rose', 'OR', 11.9, 'axl.rose@hotmail.com');
  
INSERT INTO DEMO_CUSTOMERS (CUST_FIRST_NAME, CUST_LAST_NAME, CUST_STATE, CREDIT_LIMIT, CUST_EMAIL)
  VALUES ('Duff', 'McKagan', 'WA', 200.91, 'duffy@gmail.com');
  
INSERT INTO DEMO_CUSTOMERS (CUST_FIRST_NAME, CUST_LAST_NAME, CUST_STATE, CREDIT_LIMIT, CUST_EMAIL)
  VALUES ('Izzy', 'Stradlin', 'NY', 762, 'izzy.stradlin@me.com');
  
INSERT INTO DEMO_CUSTOMERS (CUST_FIRST_NAME, CUST_LAST_NAME, CUST_STATE, CREDIT_LIMIT, CUST_EMAIL)
  VALUES ('Steven', 'Adler', 'CA', 0.99, 'stevie@me.com');
  
INSERT INTO DEMO_CUSTOMERS (CUST_FIRST_NAME, CUST_LAST_NAME, CUST_STATE, CREDIT_LIMIT, CUST_EMAIL)
  VALUES ('Steven', 'Tyler', 'NY', 500, 'steven_tyler@yahoo.com');
  
INSERT INTO DEMO_CUSTOMERS (CUST_FIRST_NAME, CUST_LAST_NAME, CUST_STATE, CREDIT_LIMIT, CUST_EMAIL)
  VALUES ('Joe', 'Perry', 'MA', 900, 'joe_perry@me.com');
  
INSERT INTO DEMO_CUSTOMERS (CUST_FIRST_NAME, CUST_LAST_NAME, CUST_STATE, CREDIT_LIMIT, CUST_EMAIL)
  VALUES ('Paul', 'McCartney', 'NY', 500, 'cute_one@me.com');
  
INSERT INTO DEMO_CUSTOMERS (CUST_FIRST_NAME, CUST_LAST_NAME, CUST_STATE, CREDIT_LIMIT, CUST_EMAIL)
  VALUES ('John', 'Lennon', 'GA', 234, 'artsy_one@me.com');
  
INSERT INTO DEMO_CUSTOMERS (CUST_FIRST_NAME, CUST_LAST_NAME, CUST_STATE, CREDIT_LIMIT, CUST_EMAIL)
  VALUES ('George', 'Harrison', 'WA', 454, 'quiet_one@me.com');
  
INSERT INTO DEMO_CUSTOMERS (CUST_FIRST_NAME, CUST_LAST_NAME, CUST_STATE, CREDIT_LIMIT, CUST_EMAIL)
  VALUES ('Ringo', 'Starr', 'VA', 875, 'drummer_guy@me.com');
  
INSERT INTO DEMO_CUSTOMERS (CUST_FIRST_NAME, CUST_LAST_NAME, CUST_STATE, CREDIT_LIMIT, CUST_EMAIL)
  VALUES ('Brian', 'Epstein', 'WV', 234, 'richard92m@me.com');
  
INSERT INTO DEMO_CUSTOMERS (CUST_FIRST_NAME, CUST_LAST_NAME, CUST_STATE, CREDIT_LIMIT, CUST_EMAIL)
  VALUES ('Allen', 'Klein', 'TX', 634, 'bigboss@me.com');
  

-- order data
SELECT * FROM DEMO_ORDERS;

INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (10, 231, '29-JUN-04', 21);
  
INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (2, 34.23, CURRENT_TIMESTAMP, 22);
  
INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (2, 23.54, '12-MAR-05', 22);
  
INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (3, 853.34, '15-MAR-04', 1);
  
INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (3, 23.23, '30-DEC-97', 34);
  
INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (3, 23.57, '24-NOV-04', 21);
  
INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (5, 764.53, '09-NOV-05', 5);
  
INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (5, 577.23, '07-JAN-04', 16);

INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (8, 862.64, '11-JUN-09', 16);
  
INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (9, 85.23, '23-JUL-04', 22);
  
INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (10, 78.89, '25-JUN-16', 17);
  
INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (10, 26.87, '27-APR-10', 18);
  
INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (10, 799.24, '20-FEB-17', 22);
  
INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (11, 13.56, CURRENT_TIMESTAMP, 54);
  
INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (13, 366.66, CURRENT_TIMESTAMP, 42);
  
INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (13, 666.66, CURRENT_TIMESTAMP, 42);
  
INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (15, 34.24, CURRENT_TIMESTAMP, 42);
  
INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (15, 766.53, CURRENT_TIMESTAMP, 54);
  
INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (15, 842.65, CURRENT_TIMESTAMP, 32);
  
INSERT INTO DEMO_ORDERS (CUSTOMER_ID, ORDER_TOTAL, ORDER_TIMESTAMP, USER_ID)
  VALUES (15, 257.47, CURRENT_TIMESTAMP, 42);
  
  
-- updates
UPDATE DEMO_ORDERS
  SET ORDER_TOTAL=233.10, USER_ID=15
  WHERE ORDER_ID=9;
  
UPDATE DEMO_ORDERS
  SET ORDER_TOTAL=542.24
  WHERE ORDER_ID=10;
  
UPDATE DEMO_ORDERS
  SET ORDER_TOTAL=67.23, USER_ID=18
  WHERE ORDER_ID=5;
  
UPDATE DEMO_ORDERS
  SET ORDER_TIMESTAMP=CURRENT_TIMESTAMP
  WHERE ORDER_ID=8;
  
UPDATE DEMO_ORDERS
  SET CUSTOMER_ID=8
  WHERE ORDER_ID=9;
  
UPDATE DEMO_CUSTOMERS
  SET CUST_FIRST_NAME='Slash'
  WHERE CUST_FIRST_NAME='Saul' AND CUST_LAST_NAME='Hudson';
  
UPDATE DEMO_CUSTOMERS
  SET CREDIT_LIMIT=2000.00
  WHERE CUSTOMER_ID=1;
  
UPDATE DEMO_CUSTOMERS
  SET CUST_FIRST_NAME='Joeseph'
  WHERE CUST_FIRST_NAME='Joe';
  
UPDATE DEMO_CUSTOMERS
  SET CREDIT_LIMIT=512.50
  WHERE CUSTOMER_ID=8;
  
UPDATE DEMO_CUSTOMERS
  SET CUST_STATE='NY'
  WHERE CUST_LAST_NAME='Marquez';
  
  
-- delete
DELETE FROM DEMO_ORDERS
  WHERE CUSTOMER_ID=15;

DELETE FROM DEMO_ORDERS
  WHERE CUSTOMER_ID=13;
  
DELETE FROM DEMO_CUSTOMERS
  WHERE CUST_LAST_NAME='Klein';
  
DELETE FROM DEMO_CUSTOMERS
  WHERE CUST_EMAIL='drummer_guy@me.com';
  
  -- queries
SELECT * FROM DEMO_ORDERS;
SELECT * FROM DEMO_CUSTOMERS;
SELECT * FROM DEMO_ORDERS INNER JOIN DEMO_CUSTOMERS ON DEMO_ORDERS.CUSTOMER_ID=DEMO_CUSTOMERS.CUSTOMER_ID;

SELECT * FROM DEMO_CUSTOMERS WHERE CREDIT_LIMIT > 2000;
SELECT * FROM DEMO_CUSTOMERS WHERE CUST_EMAIL NOT LIKE '%@%.%';

SELECT SUM(DEMO_ORDERS.ORDER_TOTAL) as "Total", DEMO_CUSTOMERS.CUST_EMAIL, DEMO_ORDERS.CUSTOMER_ID
  FROM DEMO_ORDERS
  INNER JOIN DEMO_CUSTOMERS ON DEMO_ORDERS.CUSTOMER_ID = DEMO_CUSTOMERS.CUSTOMER_ID
  GROUP BY DEMO_ORDERS.CUSTOMER_ID, DEMO_CUSTOMERS.CUST_EMAIL
  HAVING SUM(DEMO_ORDERS.ORDER_TOTAL) > 200;
  
SELECT dc.CUST_EMAIL FROM DEMO_ORDERS INNER JOIN DEMO_CUSTOMERS dc ON DEMO_ORDERS.CUSTOMER_ID = dc.CUSTOMER_ID WHERE ORDER_TOTAL > 100;
SELECT AVG(DEMO_ORDERS.ORDER_TOTAL) FROM DEMO_ORDERS;

SELECT DEMO_CUSTOMERS.CUST_EMAIL, DEMO_CUSTOMERS.CUSTOMER_ID, ORDER_ID
  FROM DEMO_CUSTOMERS
  FULL OUTER JOIN DEMO_ORDERS ON DEMO_CUSTOMERS.CUSTOMER_ID=DEMO_ORDERS.CUSTOMER_ID
  WHERE ORDER_ID IS NULL;
  
SELECT CUST_LAST_NAME, CREDIT_LIMIT
  FROM DEMO_CUSTOMERS
  ORDER BY CREDIT_LIMIT DESC;
