--3.a write 15 insert statement 
insert into DEMO_CUSTOMERS
VALUES ('1', 'LIQUN', 'ZHENG', 'AZ', '10000', 'LIQUNZHENG@LIVE.CN');
insert into DEMO_CUSTOMERS
VALUES ('2', 'DAVE', 'B', 'AZ', '10000.00', 'LIQUNZHENG@LIVE.CN');
insert into DEMO_CUSTOMERS
VALUES ('3', 'JOHN', 'E', 'AZ', '10000', 'LIQUNZHENG@LIVE.CN');
insert into DEMO_CUSTOMERS
VALUES ('4', 'DSFS', 'W', 'AZ', '10000', 'LIQUNZHENG@LIVE.CN');
insert into DEMO_CUSTOMERS
VALUES ('5', 'TRY', 'Q', 'AZ', '10000', 'LIQUNZHENG@LIVE.CN');
insert into DEMO_CUSTOMERS
VALUES ('6', 'SDFS', 'R', 'AZ', '10000', 'LIQUNZHENG@LIVE.CN');
insert into DEMO_CUSTOMERS
VALUES ('7', 'BN', 'T', 'AZ', '10000', 'LIQUNZHENG@LIVE.CN');
insert into DEMO_CUSTOMERS
VALUES ('8', 'UYY', 'YU', 'AZ', '10000', 'LIQUNZHENG@LIVE.CN');
insert into DEMO_CUSTOMERS
VALUES ('9', 'GHJ', 'I', 'AZ', '10000', 'LIQUNZHENG@LIVE.CN');
insert into DEMO_CUSTOMERS
VALUES ('10', 'CXV', 'L', 'AZ', '10000', 'LIQUNZHENG@LIVE.CN');
insert into DEMO_CUSTOMERS
VALUES ('11', 'YT', 'NB', 'AZ', '10000', 'LIQUNZHENG@LIVE.CN');
insert into DEMO_CUSTOMERS
VALUES ('12', 'RTR', 'G', 'AZ', '10000', 'LIQUNZHENG@LIVE.CN');
insert into DEMO_CUSTOMERS
VALUES ('13', 'HFG', 'F', 'AZ', '10000', 'LIQUNZHENG@LIVE.CN');
insert into DEMO_CUSTOMERS
VALUES ('14', 'KLJK', 'SA', 'AZ', '10000', 'LIQUNZHENG@LIVE.CN');
insert into DEMO_CUSTOMERS
VALUES ('15', 'LIQUN', 'JK', 'AZ', '10000', 'LIQUNZHENG@LIVE.CN');
/