CREATE TABLE USER_T
(
  U_ID NUMBER NOT NULL,
  U_USERNAME VARCHAR(20) NOT NULL,
  U_PASSWORD VARCHAR(50) NOT NULL,
  U_IMAGE BLOB NULL,
  U_S3_IMAGE VARCHAR(200) NULL,
  CONSTRAINT PK_USER PRIMARY KEY (U_ID)
);
/
INSERT INTO USER_T VALUES(1, 'TEST','1234', null, null);
/

commit;
/
