SELECT GENRE
FROM BOOKS
GROUP BY GENRE; 

SELECT COUNT(TITLE), GENRE
FROM BOOKS
GROUP BY GENRE; 

-- COUNT() IS AN AGGREGATE FUNCTION. GROUP BY IS OFTEN USED WITH AGGREGATE FUNCTIONS. 
-- GROUP BY CAN ONLY USE THE SELECTED COLUMNS

SELECT GENRE
FROM BOOKS
ORDER BY TITLE; 

-- ORDER BY CAN SORT COLUMNS EVEN IF IT'S NOT THE ONE SELECTED

/

SELECT * 
FROM BOOKS 
WHERE GENREID = 1; 

-- WHERE FILTERS ROWS, CAN'T USE AGGREGATE FUNCTIONS WITH THEM 

SELECT COUNT(TITLE), GENRE
FROM BOOKS
GROUP BY GENRE
HAVING COUNT(TITLE) > 100; 

-- HAVING ALLOWS YOU TO FILTER GROUPS OF ROWS AND USE AGGREGATE FUNCTIONS ON THEM 
