--DDL ERS Script

CREATE TABLE STATE_TYPE(

STATE_ID NUMBER PRIMARY KEY,
STATE_NAME VARCHAR(50) NOT NULL UNIQUE


);

CREATE TABLE EMPLOYEE(

EMPLOYEE_ID NUMBER PRIMARY KEY,
EMAIL VARCHAR2(50) NOT NULL UNIQUE,
PASSWORD VARCHAR2(50) NOT NULL,
FIRST_NAME VARCHAR2(100) NOT NULL,
LAST_NAME VARCHAR2(100) NOT NULL,
IS_MANAGER NUMBER(1) NOT NULL

);

CREATE TABLE REQUESTS(

REQUEST_ID NUMBER PRIMARY KEY,
STATE_ID NUMBER(1) DEFAULT 1 REFERENCES STATE_TYPE(STATE_ID),
AMOUNT NUMBER (9,2) CHECK (amount > 0.0),
PURPOSE VARCHAR2(140),
DATE_REQUESTED DATE DEFAULT SYSDATE,
REQUESTOR_ID NUMBER NOT NULL REFERENCES EMPLOYEE(EMPLOYEE_ID),
DATE_RESOLVED DATE,
RESOLVER_ID NUMBER REFERENCES EMPLOYEE(EMPLOYEE_ID)



);